---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "grafana-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: grafana
    name: grafana-pvc
  hostPath:
    path: "/home/kx.hero/KX_Data/grafana"

---
