---

  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-pvc
    labels:
      type: local
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

---
