apiVersion: v1 
kind: Service 
metadata: 
  name: {{componentName}}-service 
  namespace: {{namespace}}
spec: 
  selector: 
    app: {{componentName}} 
  ports: 
    - protocol: TCP 
      port: 1433 
      targetPort: 1433 
  type: LoadBalancer 

