alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: "http://mattermost-team-edition.{{namespace}}:8065/hooks/{{monitoringWebhookId}}"
    receivers:
      - name: default-receiver
        slack_configs:
        - channel: '#monitoring'
          send_resolved: true
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 6h

serverFiles:
  alerts:
    groups:
      - name: Instances
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 1m
            labels:
              severity: page
            annotations:
              description: '\{{ $labels.instance }} of job \{{ $labels.job }} has been down for more than 1 minute.'
              summary: 'Instance \{{ $labels.instance }} down'
      - name: NodeAlerts
        rules:
          - alert: NodeCPUUsage
            expr: (100 - (avg(irate(node_cpu{mode="idle"}[5m])) BY (instance) * 100)) > 75
            for: 2m
            labels:
              severity: alert
            annotations:
              description: '\{{$labels.instance}}: CPU usage is above 75% (current value is: \{{ $value }})'
              summary: '\{{$labels.instance}}: High CPU usage detect'
