apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: data-gitlab-postgresql-0
    labels:
      type: local
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

---

  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: redis-data-gitlab-redis-master-0
    labels:
      type: local
  spec:
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi

---
