---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "vault-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: vault
    name: data-vault-0
  hostPath:
    path: "/home/kx.hero/KX_Data/vault"

---
