apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console-{{componentName}}
  namespace: {{namespace}}
  managedFields:
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - console-{{componentName}}.{{baseDomain}}
  rules:
    - host: console-{{componentName}}.{{baseDomain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  number: 9090
