elasticsearchHosts: "https://elasticsearch-master:9200"
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: KIBANA_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        key: encryptionkey
        name: kibana-encryption-key
replicas: 1
image: "docker.elastic.co/kibana/kibana"
imageTag: "{{ elasticVersion }}"
imagePullPolicy: "IfNotPresent"
kibanaConfig:
  kibana.yml: |
    server:
      name: {{ componentName }}
      publicBaseUrl: {{ componentName }}.{{ baseDomain }}
      ssl:
        enabled: true
        key: /usr/share/kibana/config/certs/kibana.key
        certificate: /usr/share/kibana/config/certs/kibana.crt
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    elasticsearch:
      hosts: ["https://elasticsearch-master:9200"]
      ssl:
        certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
        verificationMode: certificate
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
protocol: https
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  className: "nginx"
  pathtype: ImplementationSpecific
  hosts:
    - host: {{componentName}}.{{baseDomain}}
      paths:
        - path: /
  tls:
    - hosts:
        - {{componentName}}.{{baseDomain}}

secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/kibana/config/certs
