# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    # -   id: check-yaml
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: master
    hooks:
    -   id: shellcheck

-   repo: https://github.com/tfsec/tfsec
    rev: v0.37.2
    hooks:
    -   id: tfsec
