language: node_js
node_js:
  - 14
os:
  - linux
  - osx
  - windows

before_install:
  - cd client
  - sudo apt-get -y install dpkg fakeroot

install:
  - npm ci --progress false --no-audit

script:
  - npm run lint
  - npm run make