language: node_js
node_js:
  - 14

addons:
  apt:
    packages:
      - dpkg
      - fakeroot

before_install:
  - cd client

install:
  - npm ci --progress false --no-audit

script:
  - npm run lint
  - npm run make:deb