language: node_js
node_js:
  - 14

addons:
  apt:
    packages:
      - dpkg
      - fakeroot
  sonarcloud:
    organization: "accenture-1"
    token:
      secure: "$SONARQUBE_TOKEN"
  
before_install:
  - cd client

install:
  - npm ci --progress false --no-audit

script:
  - npm run lint
  - npm run make:deb
  - sonar-scanner
