configs:
  box_version: "0.6.7"
  main_node_cpu_cores: 4
  main_node_memory: 32768
  worker_node_count: 2
  worker_node_cpu_cores: 4
  worker_node_memory: 16384
  environment_prefix: "demo1"
  dockerhub_username: ""
  dockerhub_email: ""
  dockerhub_password: ""
  kx_sync_folder_path: "/Users/<username>/KX_Share"
  kx_main_box_location: "/Users/<username>/jenkins/jenkins_home/workspace/kxascode-main-vmbox/base-vm/boxes/virtualbox-<boxversion>/kx.as.code-main-demo-<boxversion>.box"
  kx_worker_box_location: "/Users/<username>/jenkins/jenkins_home/workspace/kxascode-worker-vmbox/base-vm/boxes/virtualbox-<boxversion>/kx.as.code-worker-demo-<boxversion>.box"