clusterName: "elasticsearch"
nodeGroup: "master"
replicas: 1
image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
imageTag: "{{elasticVersion}}"
esJavaOpts: "-Xmx1g -Xms1g"
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.authc.realms.native.local.order: 0
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-stack/elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-stack/elastic-credentials
        key: username
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
persistence:
  enabled: true
ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - {{componentName}}.{{baseDomain}}
  tls: 
    - hosts:
       - {{componentName}}.{{baseDomain}}