clusterName: "elasticsearch"
nodeGroup: "master"
replicas: 1
image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
imageTag: "{{elasticVersion}}"
esJavaOpts: "-Xmx1g -Xms1g"
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
persistence:
  enabled: true
ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - {{componentName}}.{{baseDomain}}
  tls: 
    - hosts:
       - {{componentName}}.{{baseDomain}}