apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: teamcity-server-http-ingress
  namespace: {{namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - {{componentName}}.{{baseDomain}}
  rules:
  - host: {{componentName}}.{{baseDomain}}
    http:
      paths:
       - path: /
         backend:
           serviceName: teamcity-service
           servicePort: 80
