apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcitydata
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gluster-heketi-sc
  resources:
    requests:
      storage: 1Gi
