apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcitydata
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kadalu.storage-pool-1
  resources:
    requests:
      storage: 1Gi
