apiVersion: v1
kind: Service
metadata:
  name: teamcity-service
  namespace: {{namespace}}
  labels:
    app: teamcity
spec:
  selector:
    app: teamcity
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8111