grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  external_image_storage:
    provider: s3
  external_image_storage.s3:
    endpoint: http://minios3.minio-s3:9000
    bucket: grafana-image-storage
    region: eu-central-1
    access_key: {{minioAccessKey}}
    secret_key: {{minioSecretKey}}
  rendering:
    server_url: http://grafana-image-renderer-service.monitoring:8081/render
    callback_url: http://grafana.monitoring
  # auth.gitlab:
  #   enabled: true
  #   allow_sign_up: true
  #   client_id: {{grafanaGitIntegrationId}}
  #   client_secret: {{grafanaGitIntegrationSecret}}
  #   scopes: read_user
  #   auth_url: {{gitUrl}}/oauth/authorize
  #   token_url: {{gitUrl}}/oauth/token
  #   api_url: {{gitUrl}}/api/v4
  auth.generic_oauth:
    enabled: true
    #disable_login_form: true      
    client_id: grafana
    client_secret: 74b95572-aa89-4c21-a0e6-70040887fa2e
    auth_url: https://keycloak.demo1.kx-as-code.local/auth/realms/demo1.kx-as-code.local/protocol/openid-connect/auth
    token_url: https://keycloak.demo1.kx-as-code.local/auth/realms/demo1.kx-as-code.local/protocol/openid-connect/token
    api_url: https://keycloak.demo1.kx-as-code.local/auth/realms/demo1.kx-as-code.local/protocol/openid-connect/userinfo
    scopes: openid email profile
    allow_sign_up: true
    tls_skip_verify_insecure: true
  server:
    #root_url: https://{{componentName}}.{{baseDomain}}
    domain: grafana.demo1.kx-as-code.local
    root_url: https://grafana.demo1.kx-as-code.local
  extraConfigmapMounts:
    - name: certs-configmap
      mountPath: /etc/grafana/ssl/
      configMap: certs-configmap
      readOnly: true
 