---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "influxdata-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: influxdata
    name: influxdata-pvc
  hostPath:
    path: "/home/kx.hero/KX_Data/influxdata"

---
