---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-repo-data-gitlab-gitaly-0"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: gitlab
    name: repo-data-gitlab-gitaly-0
  hostPath:
    path: "/home/kx.hero/KX_Data/gitlab-ee/gitaly"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-data-gitlab-postgresql-0"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: gitlab
    name: data-gitlab-postgresql-0
  hostPath:
    path: "/home/kx.hero/KX_Data/gitlab-ee/postgres"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-redis-data-gitlab-redis-master-0"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: gitlab
    name: redis-data-gitlab-redis-master-0
  hostPath:
    path: "/home/kx.hero/KX_Data/gitlab-ee/redis"
