global:
  edition: ee
  minio:
    enabled: false
  registry:
    bucket: gitlab-registry-storage
  appConfig:
    enableUsagePing: true
    enableImpersonation: true
    defaultCanCreateGroup: true
    usernameChangingEnabled: true
    issueClosingPattern:
    defaultTheme:
    defaultProjectsFeatures:
      issues: true
      mergeRequests: true
      wiki: true
      snippets: true
      builds: true
      containerRegistry: true
    incomingEmail:
      enabled: false
      address: ""
      host: "mail.kx-as-code.local"
      port: 993
      ssl: true
      startTls: false
      user: "gitlab@kx-as-code.local"
      password:
        secret:
        key: z7wDfD6FuHp
      mailbox: inbox
      idleTimeout: 60
  smtp:
    enabled: false
    address: mail.kx-as-code.local
    port: 587
    user_name: "gitlab@kx-as-code.local"
    password:
      secret: ""
      key: password
    # domain:
    authentication: "plain"
    starttls_auto: true
    openssl_verify_mode: "peer"
  # Email persona used in email sent by GitLab
  email:
    from: ''
    display_name: GitLab
    reply_to: ''
    subject_suffix: ''

prometheus:
  install: false
gitlab-runner:
  install: false
nginx:
  controller:
    scope:
      enabled: false
redis:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
global:
  rails:
    bootsnap:
      enabled: false
# Reduce replica counts, reducing CPU & memory requirements
gitlab:
  webservice:
    minReplicas: 1
    resources:
      limits:
       memory: 1.5G
      requests:
        cpu: 100m
        memory: 900M
    workhorse:
      resources:
        limits:
          memory: 100M
        requests:
          cpu: 10m
          memory: 10M
  sidekiq:
    minReplicas: 1
    resources:
      limits:
        memory: 1.5G
      requests:
        cpu: 50m
        memory: 625M
  gitlab-shell:
    minReplicas: 1
  task-runner:
    backups:
      objectStorage:
        config:
          secret: s3cmd-config
          key: config
debug:
  addr:
    port: 5001
  prometheus:
    enabled: true
    path: '/metrics'

registry:
  hpa:
    minReplicas: 1
  service:
    type: ClusterIP
    name: registry
  storage:
    secret: registry-storage
    key: config
  name: registry.kx-as-code.local
  bucket: gitlab-registry-storage

certmanager:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
