configs:
  box_version: "0.6.7"
  main_node_cpu_cores: 2
  main_node_memory: 16384
  worker_node_count: 2
  worker_node_cpu_cores: 2
  worker_node_memory: 16384
  environment_prefix: "demo1"
  dockerhub_username: ""
  dockerhub_email: ""
  dockerhub_password: ""
