elasticsearchHosts: "http://elasticsearch-master:9200"
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-stack/elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-stack/elastic-credentials
        key: username
replicas: 1
image: "docker.elastic.co/kibana/kibana-oss"
imageTag: "{{elasticVersion}}"
imagePullPolicy: "IfNotPresent"
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"