apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: {{namespace}}
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      volumes:
      - name: registry-vol
        persistentVolumeClaim:
          claimName: docker-registry-pvc
          readOnly: false
      - name: docker-registry-certs
        secret:
          secretName: docker-registry-tls-cert
      - name: auth-vol
        secret:
           secretName: docker-registry-htpasswd
      - name: docker-registry-config
        configMap:
          name: docker-registry-config
      containers:
        - image: registry:2
          name: docker-registry
          imagePullPolicy: IfNotPresent
          env:
          - name: REGISTRY_AUTH
            value: "htpasswd"
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: "/auth/htpasswd"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/certs/registry.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/certs/registry.key"
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: registry-vol
            mountPath: /var/lib/registry
          - name: docker-registry-certs
            mountPath: "/certs/registry.crt"
            subPath: docker-registry-tls.crt
            readOnly: true
          - name: docker-registry-certs
            mountPath: "/certs/registry.key"
            subPath: tls.key
            readOnly: true
          - name: docker-registry-certs
            mountPath: "/certs/ca.crt"
            subPath: ca.crt
            readOnly: true
          - name: auth-vol
            mountPath: "/auth/htpasswd"
            subPath: docker-registry-htpasswd
            readOnly: true
          - name: docker-registry-config
            mountPath: /etc/docker/registry/config.yml
            subPath: config.yml
