apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-software-pvclaim
  namespace: jira
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
