apiVersion: apps/v1
kind: Deployment
metadata:
 name: jira-software
 namespace: jira
 labels:
  app: jira-software
spec:
 replicas: 1
 selector:
  matchLabels:
   app: jira-software
 template:
  metadata:
   labels:
    app: jira-software
  spec:
   securityContext:
    fsGroup: 1000
   initContainers:
   - name: jira-volume
     image: alpine:3.6
     command:
     - chown
     - -R
     - 1000:1000
     - /var/atlassian/application-data/jira
     volumeMounts:
     - name: jira-home
       mountPath: /var/atlassian/application-data/jira
   containers:
     - name: jira-software
       image: atlassian/jira-software
       imagePullPolicy: "IfNotPresent"
       env:
         - name: JAVA_OPTS
           value: -Xms384m -Xmx786m
         - name: CATALINA_OPTS
           value: -Datlassian.plugins.enable.wait=1200 -Duser.language=en -Duser.country=DE -Duser.timezone=UTC
       ports:
        - name: http-port
          containerPort: 8080
       volumeMounts:
         - name: jira-home
           mountPath: /var/atlassian/application-data/jira
         - name: server-xml-volume
           mountPath: /opt/atlassian/jira/conf/server.xml
           subPath: server.xml
   volumes:
     - name: jira-home
       persistentVolumeClaim:
         claimName: jira-software-pvclaim
     - name: server-xml-volume
       configMap:
         name: server-xml
