---
apiVersion: v1
kind: Namespace
metadata:
  name: selenium
  labels:
    name: selenium
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: selenium-hub-pv
  namespace: selenium
  labels:
    app: selenium-nodes
    type: local
    purpose: selenium-nodes-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kx.hero/KX_Data/K8s_Selenium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: selenium-node-pvclaim
  namespace: selenium
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
     containers:
     - name: selenium-hub
       image: selenium/hub:latest
       ports:
        - containerPort: 4444
       imagePullPolicy: "IfNotPresent"
       env:
        - name: host
          value: selenium-hub.kx-as-code.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: selenium
  labels:
    app: selenium-nodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-nodes
  template:
    metadata:
      labels:
        app: selenium-nodes
    spec:
     securityContext:
      fsGroup: 1000
     initContainers:
     - name: selenium-nodes-volume
       image: alpine:3.6
       command:
       - chown
       - -R
       - 1000:1000
       - /dev/shm
       volumeMounts:
       - name: selenium-node
         mountPath: /dev/shm
     containers:
     - name: selenium-node-chrome
       image: selenium/node-chrome:latest
       ports:
        - containerPort: 5555
       imagePullPolicy: "IfNotPresent"
       env:
       - name: HUB_PORT_4444_TCP_ADDR
         value: selenium-hub
       - name: HUB_PORT_4444_TCP_PORT
         value: "4444"
       volumeMounts:
         - name: selenium-node
           mountPath: /dev/shm
     volumes:
       - name: selenium-node
         persistentVolumeClaim:
           claimName: selenium-node-pvclaim
---
piVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-firefox
  namespace: selenium
  labels:
    app: selenium-nodes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-nodes
  template:
    metadata:
      labels:
        app: selenium-nodes
    spec:
     securityContext:
      fsGroup: 1000
     initContainers:
     - name: selenium-nodes-volume
       image: alpine:3.6
       command:
       - chown
       - -R
       - 1000:1000
       - /dev/shm
       volumeMounts:
       - name: selenium-node
         mountPath: /dev/shm
     containers:
     - name: selenium-node-firefox
       image: selenium/node-firefox:latest
       ports:
        - containerPort: 5900
       imagePullPolicy: "IfNotPresent"
       env:
       - name: "HUB_PORT_4444_TCP_ADDR"
         value: "selenium-hub"
       - name: "HUB_PORT_4444_TCP_PORT"
         value: "4444"
       volumeMounts:
         - name: selenium-node
           mountPath: /dev/shm
     volumes:
       - name: selenium-node
         persistentVolumeClaim:
           claimName: selenium-node-pvclaim
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  type: ClusterIP
  ports:
   - name: hub
     port: 4444
     targetPort: 4444
     protocol: TCP
  selector:
    app: selenium-hub
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: selenium-hub-ingress
  namespace: selenium
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - selenium-hub.kx-as-code.local
  rules:
  - host: selenium-hub.kx-as-code.local
    http:
      paths:
       - path: /
         backend:
           serviceName: selenium-hub
           servicePort: hub
---
