global:
  datacenter: kx-as-code

client:
  enabled: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
  storage: 1Gi
  storageClass: local-storage

resources:
  requests:
    memory: "25Mi"
    cpu: "20m"
  limits:
    memory: "50Mi"
    cpu: "20m"

    ui:
      enabled: "true"
      service:
        enabled: "true"
        type: "ClusterIP"

