filebeatConfig:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: \${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elastic-elasticsearch:9200}'
      ssl:
        certificate_authorities: ["certs/ca.crt"]
        certificate: certs/elasticsearch.crt
        key: certs/elasticsearch.key
    setup.kibana:
      host: "https://elastic-kibana:5601"
      ssl:
        enabled: true
        certificate_authorities: ["certs/ca.crt"]
        certificate: certs/kibana.crt
        key: certs/kibana.key
image: "docker.elastic.co/beats/filebeat"
imageTag: "{{elasticVersion}}"
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "1000m"
    memory: "200Mi"
secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/filebeat/config/certs