---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "influxdb-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: tick-stack
    name: influxdb-pvc
  hostPath:
    path: "/home/kx.hero/KX_Data/tick-stack/influxdb"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "chronograf-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: tick-stack
    name: chronograf-chronograf
  hostPath:
    path: "/home/kx.hero/KX_Data/tick-stack/chronograf"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "kapacitor-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: tick-stack
    name: kapacitor-pvc
  hostPath:
    path: "/home/kx.hero/KX_Data/tick-stack/kapacitor"

---
