# Needed for the docker in docker CI builds to work. The Gitab docker service did not work. Will revisit this point again in future.
gitlab-runner:
  preEntrypointScript: |
      echo -e '    [[runners.kubernetes.volumes.host_path]]\n      name = "docker"\n      mount_path = "/var/run/docker.sock" '>> /home/gitlab-runner/.gitlab-runner/config.toml

## https://docs.gitlab.com/charts/charts/globals#configure-appconfig-settings
## Rails based portions of this chart share many settings
appConfig:
  ## https://docs.gitlab.com/charts/charts/globals#general-application-settings
  omniauth:
    enabled: true
    autoSignInWithProvider:
    syncProfileFromProvider: []
    syncProfileAttributes: ['email']
    allowSingleSignOn: ['saml']
    blockAutoCreatedUsers: true
    autoLinkLdapUser: false
    autoLinkSamlUser: false
    autoLinkUser: []
    externalProviders: []
    allowBypassTwoFactor: []
    providers:
    # - secret: gitlab-google-oauth2
    #   key: provider
    ## https://docs.gitlab.com/charts/charts/globals#configure-appconfig-settings
      - { name: 'openid_connect',
          label: 'Keycloak',
          args: {
            name: 'openid_connect',
            scope: ['openid','profile','email'],
            response_type: 'code',
            issuer: "https://keycloak.{{baseDomain}}/auth/realms/{{baseDomain}}",
            discovery: true,
            client_auth_method: 'query',
            send_scope_to_token_endpoint: false,
            user_response_structure: {
              id_path: 'preferred_username',
              attributes: {  nickname:  'preferred_username'  }
            },
            client_options: {
              identifier: '{{clientId}}',
              secret: '{{clientSecret}}',
              redirect_uri: 'https://gitlab.{{baseDomain}}/users/auth/openid_connect/callback'
            }
          }
        }