apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-image-renderer-ingress
  namespace: {{namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - {{componentName}}.{{baseDomain}}
  rules:
  - host: {{componentName}}.{{baseDomain}}
    http:
      paths:
       - path: /
         backend:
           serviceName: grafana-image-renderer-service
           servicePort: 8081
