apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer-service
  namespace: {{namespace}}
  labels:
    app: grafana-image-renderer
spec:
  type: ClusterIP
  ports:
   - port: 8081
     targetPort: 8081
     protocol: TCP
  selector:
    app: grafana-image-renderer