apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-software-pvclaim
  namespace: {{namespace}}
spec:
  storageClassName: gluster-heketi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
