apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-server-pvclaim
  namespace: confluence
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
