apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hipster-frontend-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{componentName}}.{{baseDomain}}
  rules:
    - host: {{componentName}}.{{baseDomain}}
      http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: Prefix
