---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    name: nexus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
  labels:
    app: nexus
    type: local
    purpose: nexus-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kx.hero/KX_Data/Nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvclaim
  namespace: nexus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
       - name: nexus-volume
         image: alpine:3.6
         command:
          - chown
          - -R
          - 1000:1000
          - /nexus_data
         volumeMounts:
          - name: nexus-data
            mountPath: /nexus_data
      containers:
       - name: sonytype-nexus
         image: sonatype/nexus3
         imagePullPolicy: "IfNotPresent"
# to add more memory to nexus or overwrite the default memory settings please uncomment next lines and add appropriate values
         env:
          - name: INSTALL4J_ADD_VM_PARAMS
            value: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g"
         ports:
          - name: http-port
            containerPort: 8081
         volumeMounts:
          - name: nexus-data
            mountPath: /nexus_data
      volumes:
       - name: nexus-data
         persistentVolumeClaim:
           claimName: nexus-pvclaim
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    app: nexus
spec:
  type: ClusterIP
  ports:
   - port: 8081
     targetPort: 8081
     protocol: TCP
  selector:
    app: nexus
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - nexus.kx-as-code.local
  rules:
  - host: nexus.kx-as-code.local
    http:
      paths:
       - path: /
         backend:
           serviceName: nexus-service
           servicePort: 8081
