apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: confluence-ingress
  namespace: {{namespace}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{componentName}}.{{baseDomain}}
  rules:
  - host: {{componentName}}.{{baseDomain}}
    http:
      paths:
       - path: /
         backend:
           serviceName: confluence-server-service
           servicePort: 8090
