apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-server-pvclaim
  namespace: {{namespace}}
spec:
  storageClassName: kadalu.storage-pool-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
