extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
daemonset:
  hostNetworking: true
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: elasticsearch
        metricsets:
          - ccr
          - cluster_stats
          - enrich
          - index
          - index_recovery
          - index_summary
          - ml_job
          - node_stats
          - shard
        period: 30s
        hosts: ["https://elasticsearch-master:9200"]
        ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca.crt"]
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
        xpack.enabled: true
      - module: kubernetes
        metricsets:
          - container
          - node
          - pod
          - system
          - volume
        period: 30s
        host: "${NODE_NAME}"
        hosts: ["https://${NODE_NAME}:10250"]
        ssl.verification_mode: none
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        processors:
        - add_kubernetes_metadata: ~
      - module: kubernetes
        enabled: true
        metricsets:
          - event
      - module: system
        period: 30s
        metricsets:
          - cpu
          - load
          - memory
          - network
          - process
          - process_summary
        processes: ['.*']
        process.include_top_n:
          by_cpu: 5
          by_memory: 5
      - module: system
        period: 1m
        metricsets:
          - filesystem
          - fsstat
        processors:
        - drop_event.when.regexp:
            system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
      output.elasticsearch:
        hosts: '${ELASTICSEARCH_HOSTS:https://elasticsearch-master:9200}'
        ssl:
          certificate_authorities: ["/usr/share/metricbeat/config/certs/ca.crt"]
          certificate: /usr/share/metricbeat/config/certs/elasticsearch.crt
          key: /usr/share/metricbeat/config/certs/elasticsearch.key
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
      setup.kibana:
        host: "https://elastic-kibana-kibana:5601"
        ssl:
          enabled: true
          certificate_authorities: ["/usr/share/metricbeat/config/certs/ca.crt"]
          certificate: /usr/share/metricbeat/config/certs/kibana.crt
          key: /usr/share/metricbeat/config/certs/kibana.key
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
image: "docker.elastic.co/beats/metricbeat"
imageTag: "{{elasticVersion}}"
protocol: https
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "1000m"
    memory: "200Mi"
secretMounts:
  - name: elastic-certificates
    secretName: elastic-certificates
    path: /usr/share/metricbeat/config/certs