apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: {{ namespace }}
  labels:
    app: {{ componentName }}
  annotations:
    volume.beta.kubernetes.io/storage-class: local-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
