name: release-process
on: workflow_dispatch

env:
  RELEASE: v0.8.10
  SINCE_TAG: v0.8.9

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          stripGeneratorNotice: true
          pullRequests: false
          releaseUrl: https://github.com/Accenture/kx.as.code/releases/tag/${{ env.RELEASE }}
          sinceTag: ${{ env.SINCE_TAG }}
      - name: Get CHANGELOG
        id: vars
        run: |
          set -x
          FULL_CHANGELOG=$(cat ./CHANGELOG.md | sed '/Full Changelog/d' | awk -v RS='\n\n\n' 1)
          HISTORY_CHANGELOG=$(echo -e "$FULL_CHANGELOG" | sed '/Changelog/d')
          SHORT_CHANGELOG=$(echo -e "$FULL_CHANGELOG" | awk '/\*\*/ {exit} {print}' | sed 's/#[^ ] *//g' | sed '/Changelog/d')
          SHORT_CHANGELOG="${SHORT_CHANGELOG//'%'/'%25'}"
          SHORT_CHANGELOG="${SHORT_CHANGELOG//$'\n'/'%0A'}"
          SHORT_CHANGELOG="${SHORT_CHANGELOG//$'\r'/'%0D'}"
          SHORT_CHANGELOG="${SHORT_CHANGELOG//$'\r'/'%0D'}"
          echo ::set-output name=changelog::$(echo -e "$SHORT_CHANGELOG\n")
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md
      - name: Archive-HISTORY.md
        uses: actions/upload-artifact@v3
        with:
          name: HISTORY.md
          path: ./HISTORY.md
      - name: Send CHANGELOG to Discord
        env:
          DISCORD_WEBHOOK_SECRET_NAME:  WEBHOOK_URL_${GITHUB_REF##*/,,}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.vars.outputs.changelog }}"
      - name: Commit CHANGELOG Changes
        run: |
          echo "::set-env name=DISCORD_WEBHOOK::${{ secrets[env.DISCORD_WEBHOOK_SECRET_NAME] }}"
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add ./CHANGELOG.md ./HISTORY.md
          git commit -m 'Update Changelog and History file for release ${{ env.RELEASE }}'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Upload Changelog ${{ env.RELEASE }}
          title: Upload Changelog
          body: Upload Changelog and History file for release ${{ env.RELEASE }}
          branch: feature/changelog-for-${{ env.RELEASE }}
          token: ${{ secrets.GH_TOKEN }}
