name: Changelog
on: workflow_dispatch 

env:
  RELEASE: v0.8.9
  SINCE_TAG: v0.8.6
  
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          stripGeneratorNotice: true
          releaseUrl: https://github.com/Accenture/kx.as.code/releases/tag/${{ env.RELEASE }}
          sinceTag: ${{ env.SINCE_TAG }}
      - name: Get CHANGELOG
        id: vars
        run: |
          set -x
          FULL_CHANGELOG=$(cat ./CHANGELOG.md | sed '/Full Changelog/d' | awk -v RS='\n\n\n' 1)
          HISTORY_CHANGELOG=$(echo $FULL_CHANGELOG | sed '/Changelog/d')
          SHORT_CHANGELOG=$(echo $FULL_CHANGELOG | awk '/\*\*/ {exit} {print}' | sed 's/#[^ ] *//g')
          echo -e $FULL_CHANGELOG | sudo tee ./CHANGELOG.md
          if [ ! -f ./HISTORY.md ]; then
            echo -e "# History\n\nHistory is the past, the future is [here](https://accenture.github.io/kx.as.code/Overview/Future-Roadmap/)\n\n" | sudo tee ./HISTORY.md
          fi
          if [ -z $(cat ./HISTORY.md | grep "${RELEASE}") ]; then
            echo -e "$HISTORY_CHANGELOG" | sudo tee -a ./HISTORY.md
          fi
          SHORT_CHANGELOG="${SHORT_CHANGELOG//'%'/'%25'}"
          SHORT_CHANGELOG="${SHORT_CHANGELOG//$'\n'/'%0A'}"
          SHORT_CHANGELOG="${SHORT_CHANGELOG//$'\r'/'%0D'}"
          SHORT_CHANGELOG="${SHORT_CHANGELOG//$'\r'/'%0D'}"
          echo ::set-output name=changelog::$(echo $SHORT_CHANGELOG)
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md
      - name: Archive-HISTORY.md
        uses: actions/upload-artifact@v3
        with:
          name: HISTORY.md
          path: ./HISTORY.md
      - name: Send CHANGELOG to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.vars.outputs.changelog }}"

