name: Changelog
on: workflow_dispatch 

env:
  RELEASE: v0.8.9
  SINCE_TAG: v0.8.6
  
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          stripGeneratorNotice: true
          release-url: https://github.com/Accenture/kx.as.code/releases/tag/${{ env.RELEASE }}
          sinceTag: ${{ env.SINCE_TAG }}
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md   
      - name: Get CHANGELOG
        id: vars
        run: |
          set -x
          CHANGELOG=$(cat ./CHANGELOG.md | awk '/\*\*/ {exit} {print}')
          if [ ! -f ./HISTORY.md ]; then
            echo -e "# History\n\nHistory is the past, the future is [here](https://accenture.github.io/kx.as.code/Overview/Future-Roadmap/)\n\n"
          fi
          if [ -z $(cat ./HISTORY.md | grep ${RELEASE}") ]; then
            cat ./CHANGELOG.md | tee -a ./HISTORY.md
          fi
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo ::set-output name=changelog::$(echo $CHANGELOG)
      - name: Archive-HISTORY.md
        uses: actions/upload-artifact@v3
        with:
          name: HISTORY.md
          path: ./HISTORY.md
      - name: Send CHANGELOG to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.vars.outputs.changelog }}"

