name: Changelog
on: workflow_dispatch 

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          headerLabel: "# 📑 Changelog"
          breakingLabel: '### 💥 Breaking'
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          stripGeneratorNotice: true
          sinceTag: v0.8.6
      - name: Archive CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md        
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: LeGitHubDeTai/github-to-discord@main
      env:
        DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        DISCORD_USERNAME: Patrick Delamere
        DISCORD_AVATAR: https://raw.githubusercontent.com/LeGitHubDeTai/github-to-discord/main/icon.png
        MESSAGE_TITLE: New Version
        MESSAGE_DESCRIPTION: New Release Note!
        MESSAGE_URL: https://github.com/Accenture/kx.as.code
        MESSAGE_COLOR: 5814783
