name: Changelog
on: workflow_dispatch 

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          output: CHANGELOG.md
          headerLabel: "# 📑 Changelog"
          breakingLabel: '### 💥 Breaking'
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          stripGeneratorNotice: true
          sinceTag: v0.8.6
      - name: Archive-CHANGELOG.md
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: ./CHANGELOG.md   
      - name: Get CHANGELOG
        id: vars
        run: |
          set -x
          CHANGELOG=$(cat ./CHANGELOG.md | awk '/###/ {exit} {print}')
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo ::set-output name=changelog::$(echo $CHANGELOG)
      - name: Send CHANGELOG to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
        uses: Ilshidur/action-discord@master
        with:
          args: "${{ steps.vars.outputs.changelog }}"
