---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "elasticsearch-master-pv"
spec:
  storageClassName: manual
  capacity:
    storage: "30Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: elastic-stack
    name: elasticsearch-master-elasticsearch-master-0
  hostPath:
    path: "/home/kx.hero/KX_Data/elastic-stack/elasticsearch"

---
